# Generated by Django 5.2.3 on 2025-07-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='snippet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
