# Generated by Django 5.2.3 on 2025-07-01 02:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blogs_image_blogs_snippet_blogs_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created']},
        ),
    ]
