# Generated by Django 5.2.3 on 2025-07-03 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_blogs_blog_alter_blog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.CreateModel(
            name='BlogBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('text', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.blog')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
