# Generated by Django 5.2.3 on 2025-11-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bookingsnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsnapshot',
            name='user',
        ),
        migrations.AddField(
            model_name='bookingsnapshot',
            name='session_id',
            field=models.CharField(db_index=True, default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
