# Generated by Django 5.2.3 on 2025-12-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_bookingsnapshot_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='cash', max_length=50),
        ),
    ]
