# Generated by Django 5.2.3 on 2025-12-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paymentlink',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
