# Generated by Django 5.2.3 on 2026-01-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_booking_email_alter_booking_furnished_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='selected_areas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
